defaults:
    - _self_
    - general : general_default
    - model : discrete
    - train : train_default
    - dataset : younger

hydra:
  job:
    chdir: True
  run:
    dir: /younger/NIPS2024/DiGress/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${general.name}




